version: "3.9"

name: laravel-inertia-stack

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app-php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:Z
      - composer-cache:/tmp/composer
    env_file:
      - .env
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.27-alpine
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:Z
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mariadb:11.4
    container_name: app-db
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: deprescreen
        MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - db-data:/var/lib/mysql
    # ports:
    #   - "3306:3306"

  redis:
    image: redis:7-alpine
    container_name: app-redis
    restart: unless-stopped
    # ports:
    #   - "16379:6379"

  node:
    image: node:20-alpine
    container_name: app-node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

#   Opsional: worker terpisah, jika tidak ingin supervisor di 'app'
  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app-queue
    restart: unless-stopped
    depends_on:
      - redis
      - db
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      # kalau TIDAK menyalin queue-worker.ini saat build, map-kan via volume:
      # - ./docker/php/queue-worker.ini:/etc/supervisor.d/queue-worker.ini:ro
    command: ["supervisord", "-c", "/etc/supervisord.conf"]

volumes:
  db-data:
  composer-cache:
